version: "3"
services:
  postgres:
    build: ./database
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: admin123
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
  go-api:
    build: ./backend
    ports:
      - "8081:8081"
    depends_on:
      - postgres
  react-app:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - go-api
